[project]
name = "creating-brick-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.1, <3.12"
dependencies = [
    "buildingmotif>=0.3.0",
    "pandas>=2.0.3",
    "pip>=25.0",
    "pyshacl>=0.26.0",
    "rdflib>=7.1.3",
]
